###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=framework
            - MYSQL_USER=alp
            - MYSQL_PASSWORD=alp
        ports:
            - '28002:3306'
        networks:
            - framework-network

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '28000:80'
        networks:
            - framework-network

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
        networks:
            - framework-network

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        networks:
            - framework-network
networks:
  framework-network:
    name: framework-network
    driver: bridge
